### ISSUE TITLE
Open Handle detected in Jest test using SDK

### ISSUE THREAD

**Issue by thejerrybao** [evervault/evervault-node#171]
We're using the SDK in a Nest Service and then testing the service with Jest. In the test, we're seeing an open handle from importing `Evervault` when running the test.

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  CustomGC

    > 1 | import Evervault from "@evervault/sdk";
        | ^
      2 | import { Injectable } from "@nestjs/common";
      3 |

      at Runtime._loadModule (../../../node_modules/.pnpm/jest-runtime@29.6.4/node_modules/jest-runtime/build/index.js:1018:29)
      at Object.<anonymous> (../../../node_modules/.pnpm/evervault-attestation-bindings@0.3.2/node_modules/evervault-attestation-bindings/index.js:110:25)
      at loadAttestationBindings (../../../node_modules/.pnpm/@evervault+sdk@5.1.4/node_modules/@evervault/sdk/lib/utils/attest.js:11:12)
      at Object.<anonymous> (../../../node_modules/.pnpm/@evervault+sdk@5.1.4/node_modules/@evervault/sdk/lib/utils/attest.js:7:29)
      at Object.<anonymous> (../../../node_modules/.pnpm/@evervault+sdk@5.1.4/node_modules/@evervault/sdk/lib/utils/index.js:9:11)
      at Object.<anonymous> (../../../node_modules/.pnpm/@evervault+sdk@5.1.4/node_modules/@evervault/sdk/lib/index.js:12:5)
      at Object.<anonymous> (auth/evervault.service.ts:1:1)
```

Any ideas on how to fix this or if this is an issue?

**Comment by lfarrel6** [comment]
Thanks for reporting! 

As your stack trace shows, this issue is with the dynamic import of the `evervault-attestation-bindings` from our `attest.js` module in the Node SDK ([permalink](https://github.com/evervault/evervault-node/blob/60720f11c553572fad819efd28bcd54d83a94b36/lib/utils/attest.js#L7)). This dependency is optional, and only required if you are using our Enclaves product so the quickest resolution is to omit optional dependencies when installing the Evervault SDK - `npm install @evervault/sdk --omit=optional` if you're using npm.

A bit more context: our attestation bindings use a Rust crate exposed via native bindings for Node, as well as several other languages. The native bindings are platform specific, so the top level `evervault-attestation-bindings` dynamically resolves the appropriate package (we're using [napi-rs](https://github.com/napi-rs/napi-rs) for this, you can read more about it in [their docs](https://napi.rs/docs/introduction/getting-started#deep-dive)). This involves checking the file system for the appropriate, which doesn't seem to play nicely with the jest runtime's module loader.

I've replicated the issue in a local test suite, though I'm yet to see jest fail to exit so it may be a false positive. Has this warning resulted in hanging tests for you? Regardless, we'll see if it can be fixed.

**Comment by thejerrybao** [comment]
> I've replicated the issue in a local test suite, though I'm yet to see jest fail to exit so it may be a false positive. Has this warning resulted in hanging tests for you?

It has resulted in hanging tests for us; one test in particular lasts much longer than it should have.

Is there a way to omit the optional dependency in `package.json`? I can't seem to figure out how to do so but maybe I'm missing something...

**Comment by lfarrel6** [comment]
Would you mind sharing a repro of a hanging test? What other features of the SDK are you using?

Re: optional dependencies, the only way to omit them is during the initial install (using `npm install @evervault/sdk --omit=optional`). There isn't a way to omit optional dependencies through the package.json. The support is limited to per package at install, or for all dependencies at the project level (i.e. through the `--omit` flag, or through the npm config). 

We're going to explore ways to remove our optional dependencies from the package, and move them to a plugin.
